name: Initialize GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy-pages.yml'
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

jobs:
  init-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Enable GitHub Pages
      uses: actions/github-script@v7
      with:
        script: |
          try {
            // Enable GitHub Pages with GitHub Actions as source
            await github.rest.repos.createPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: 'main',
                path: '/'
              },
              build_type: 'workflow'
            });
            console.log('GitHub Pages enabled successfully');
          } catch (error) {
            if (error.status === 409) {
              console.log('GitHub Pages already enabled');
              // Try to update the configuration
              try {
                await github.rest.repos.updateInformationAboutPagesSite({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  source: {
                    branch: 'main',
                    path: '/'
                  },
                  build_type: 'workflow'
                });
                console.log('GitHub Pages configuration updated');
              } catch (updateError) {
                console.log('Failed to update Pages config:', updateError.message);
              }
            } else {
              console.error('Failed to enable GitHub Pages:', error.message);
              throw error;
            }
          }

    - name: Trigger deployment
      uses: actions/github-script@v7
      with:
        script: |
          // Trigger the deploy-pages workflow
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'deploy-pages.yml'
          });
          console.log('Deployment workflow triggered');